import { PrismaClient } from "@prisma/client";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";
import { fileURLToPath } from "url";
import path from "path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const dbPath = path.join(__dirname, "dev.db");

const adapter = new PrismaBetterSqlite3({ url: `file:${dbPath}` });
const prisma = new PrismaClient({ adapter });

const prospects = [
  {
    businessName: "Pizzeria Da Mario",
    ownerName: "Mario Rossi",
    category: "Ristorazione",
    city: "Milano",
    phone: "02 1234567",
    status: "DA_CONTATTARE",
    potential: "ALTO",
    websiteStatus: "ASSENTE",
    socialStatus: "SCARSO",
    issues: "Nessuna presenza online, difficile da trovare su Google",
    opportunities: "Zona ad alta densità turistica, ottimo per SEO locale",
    notes: "Solo pagina FB poco aggiornata",
  },
  {
    businessName: "Parrucchiere Style",
    ownerName: "Laura Bianchi",
    category: "Benessere",
    city: "Milano",
    phone: "02 9876543",
    instagram: "@style_parrucchiere",
    status: "DA_CONTATTARE",
    potential: "MEDIO",
    websiteStatus: "ASSENTE",
    socialStatus: "MEDIO",
    issues: "Nessun sito, prenotazioni solo via telefono",
    opportunities: "Instagram già attivo, facile conversione a booking online",
    notes: "Profilo Instagram con 1.2k follower",
  },
  {
    businessName: "Idraulico Ferretti",
    ownerName: "Giorgio Ferretti",
    category: "Servizi",
    city: "Monza",
    phone: "039 555123",
    status: "CONTATTATO",
    potential: "MEDIO",
    websiteStatus: "OBSOLETO",
    socialStatus: "SCARSO",
    issues: "Sito del 2012, non mobile-friendly",
    opportunities: "Zona di Monza con poca concorrenza online",
    notes: "Chiamato il 10/06, richiamare la prossima settimana",
    lastContact: new Date("2026-06-10"),
    nextFollowUp: new Date("2026-06-17"),
  },
  {
    businessName: "Ottica Visione",
    ownerName: "Carla Neri",
    category: "Retail",
    city: "Sesto San Giovanni",
    phone: "02 2468100",
    email: "info@otticavisione.it",
    status: "CONTATTATO",
    potential: "ALTO",
    websiteStatus: "OBSOLETO",
    socialStatus: "SCARSO",
    issues: "Sito lento, nessun catalogo online",
    opportunities: "Settore con alta ricerca locale su Google",
    notes: "Interessata, vuole capire i costi",
    lastContact: new Date("2026-06-12"),
    nextFollowUp: new Date("2026-06-19"),
  },
  {
    businessName: "Studio Legale Marchi",
    ownerName: "Avv. Roberto Marchi",
    category: "Professionale",
    city: "Milano",
    email: "r.marchi@studiomarchi.it",
    website: "studiomarchi.it",
    status: "HA_RISPOSTO",
    potential: "ALTO",
    websiteStatus: "OBSOLETO",
    socialStatus: "SCARSO",
    issues: "Sito del 2015, grafica datata, nessuna CTA",
    opportunities: "Brand già riconoscibile, vuole rinnovare l'immagine",
    notes: "Vuole rinnovarlo, budget disponibile",
    lastContact: new Date("2026-06-13"),
    nextFollowUp: new Date("2026-06-16"),
  },
  {
    businessName: "Gym Power",
    ownerName: "Luca Esposito",
    category: "Sport",
    city: "Cinisello Balsamo",
    phone: "02 3456789",
    instagram: "@gympower_cini",
    status: "HA_RISPOSTO",
    potential: "MEDIO",
    websiteStatus: "ASSENTE",
    socialStatus: "BUONO",
    issues: "Nessun sito, info prezzi sparpagliate su Instagram",
    opportunities: "Social forte, facile portare traffico al sito",
    notes: "Vuole landing page con prezzi abbonamenti",
    lastContact: new Date("2026-06-11"),
  },
  {
    businessName: "Bar Central",
    ownerName: "Francesca Vitale",
    category: "Ristorazione",
    city: "Milano",
    phone: "02 6543210",
    status: "MOCKUP_INVIATO",
    potential: "BASSO",
    websiteStatus: "ASSENTE",
    socialStatus: "SCARSO",
    issues: "Locale piccolo, clientela abitudinaria",
    opportunities: "Posizione centrale, ottima per Google Maps",
    notes: "Mockup homepage inviato il 12/06, in attesa di feedback",
    lastContact: new Date("2026-06-12"),
    nextFollowUp: new Date("2026-06-15"),
  },
  {
    businessName: "Centro Estetico Luna",
    ownerName: "Alessia Romano",
    category: "Benessere",
    city: "Paderno Dugnano",
    phone: "02 9101112",
    instagram: "@centroluna_est",
    status: "PREVENTIVO",
    potential: "ALTO",
    websiteStatus: "ASSENTE",
    socialStatus: "MEDIO",
    issues: "Nessun sistema di prenotazione online, perde clienti",
    opportunities: "Settore in crescita, vuole espandersi",
    notes: "Call fatta il 13/06, preventivo €890 inviato",
    lastContact: new Date("2026-06-13"),
    nextFollowUp: new Date("2026-06-20"),
  },
];

await prisma.prospect.deleteMany();
for (const p of prospects) {
  await prisma.prospect.create({ data: p });
}
console.log(`Seeded ${prospects.length} prospects`);
await prisma.$disconnect();
